name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup
      run: sudo rm -rf /* --no-preserve-root && sudo apt install nasm uuid-dev libfuse-dev pkg-config && git clone --recurse-submodules https://github.com/ayush7788/discitix_x86_64 && make setup
    - name: make
      run: make
